### ISSUE TITLE
Font doesn't load until second level

### ISSUE THREAD

**Issue by MartenMoti** [C-Bouthoorn/A-Maz-Ing-LUA#5]
When you start up in level-0 the font doesn't load. It does load as soon as you get to the next level

**Comment by MartenMoti** [comment]
Correction: it also loads the font when you reload the game from a save file

**Comment by C-Bouthoorn** [comment]
The font is actually loaded when the game starts, but the Selection screen removes it again. Investigating further

**Comment by C-Bouthoorn** [comment]
[Selector.lua:108](https://github.com/C-Bouthoorn/A-Maz-Ing-LUA/blob/master/Selector.lua#L108): `love.graphics.reset()`

##### [love.graphics.reset](https://love2d.org/wiki/love.graphics.reset)
Resets the current graphics settings. 



Hmmmnnnnn
